### ISSUE TITLE
Affiliate Dashboard Conversation Report Modifications

### ISSUE THREAD

**Issue by tapabratainfluxiq** [debasiskar-devel-007/unrealityofdeath-angular#1]
1. AFFILIATE DASHBOARD-CLICK AND CONVERSION REPORT PREVIEW DETAILS-MENTION USER NAME WHO FILLS UP THE LANDING PAGE.
2. AFFILIATE DASHBOARD-CAMPAIGN LIST AND ADD CAMPAIGN MODAL RESPONSIVE ISSUE.
3. Last login block common component in Affiliate Dashboard.

**Comment by sanketinfluxiq** [comment]
Solved all the issues.
